language: go
go:
- tip
os:
- linux
- osx
install:
- go get -t -v ./...
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go get golang.org/x/tools/cmd/cover; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go get github.com/mattn/goveralls; fi
script:
- go test -v -covermode=count -coverprofile=coverage.out ./...
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN; fi
