version: 0.0.1_{build}
build: off
platform: x64
clone_folder: c:\gopath\src\github.com\OpenPeeDeeP\xdg
environment:
  GOPATH: c:\gopath
stack: go 1.11
install:
  - go get -t -v ./...
  - cinst codecov
before_test:
  - go vet ./...
test_script:
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt
on_success:
  - codecov -f coverage.txt
