version: 0.0.1_{build}
platform: x64
clone_folder: c:\gopath\src\github.com\OpenPeeDeeP\xdg
environment:
  GOPATH: c:\gopath
install:
- echo %PATH%
- echo %GOPATH%
- set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
- go version
- go env
- go get -t -v ./...
build_script:
- go test -v -race -covermode=atomic -coverprofile=coverage.txt
on_success:
- bash <(curl -s https://codecov.io/bash)
